// One-time seed: called during first-run provisioning to populate Firestore
// with demo clients, leads, and customers.
import { doc, setDoc, collection } from "firebase/firestore";
import { db } from "./firebase";

const seedClients = [
  {
    id: "c1",
    srNo: 1,
    date: "2026-05-02",
    mvNo: "MH12AB1234",
    application: "Renewal",
    work: "Insurance + Fitness",
    name: "Vikram Malhotra",
    status: "Completed",
    mo: "9876501234",
    insurance: "2027-05-01",
    fitness: "2027-04-20",
    tax: "Paid",
    co: "Rajesh M.",
    assignee: "staff",
    serviceType: "Insurance",
    serviceStatus: "In Progress",
    serviceDueDate: "2027-05-01",
  },
  {
    id: "c2",
    srNo: 2,
    date: "2026-05-09",
    mvNo: "MH14XY7788",
    application: "Transfer",
    work: "Ownership transfer",
    name: "Anita Desai",
    status: "In Progress",
    mo: "9876512345",
    insurance: "2026-11-12",
    fitness: "2026-09-30",
    tax: "Due",
    co: "—",
    assignee: "priya",
    serviceType: "RC Transfer",
    serviceStatus: "In Progress",
    serviceDueDate: "2026-11-12",
  },
  {
    id: "c3",
    srNo: 3,
    date: "2026-05-14",
    mvNo: "MH04CD9090",
    application: "Permit",
    work: "Commercial permit",
    name: "Karan Deshmukh",
    status: "Pending",
    mo: "9876523456",
    insurance: "2026-08-21",
    fitness: "2026-12-15",
    tax: "Paid",
    co: "Logistics Co.",
    assignee: "rahul",
    serviceType: "Permit",
    serviceStatus: "Pending",
    serviceDueDate: "2026-08-21",
  },
];

const seedLeads = [
  {
    id: "l1",
    srNo: 1,
    date: "2026-05-15",
    mvNo: "—",
    application: "Inquiry",
    work: "New registration",
    name: "Priya Shah",
    status: "Pending",
    mo: "9988776655",
    insurance: "—",
    fitness: "—",
    tax: "—",
    co: "—",
    assignee: "staff",
    serviceType: "Insurance",
    serviceStatus: "Pending",
    serviceDueDate: "2026-06-15",
  },
  {
    id: "l2",
    srNo: 2,
    date: "2026-05-16",
    mvNo: "MH02EF3344",
    application: "Inquiry",
    work: "Insurance renewal",
    name: "Sandeep Kulkarni",
    status: "In Progress",
    mo: "9123456780",
    insurance: "2026-06-30",
    fitness: "—",
    tax: "—",
    co: "—",
    assignee: "priya",
    serviceType: "Insurance",
    serviceStatus: "In Progress",
    serviceDueDate: "2026-06-30",
  },
];

const seedCustomers = [
  {
    id: "cu1",
    name: "Rajesh Sharma",
    address: "100 FC Road, Pune",
    mobile: "+91 9000000000",
    email: "rajesh.sharma@mail.com",
    vehicles: [
      {
        id: "v1a",
        mvNo: "MH-09-BH-0137",
        work: "Insurance Renewal",
        insurance: "2027-06-01",
        fitness: "2027-05-10",
        tax: "Paid",
        status: "Completed",
      },
    ],
    serviceType: "Insurance",
    serviceStatus: "Completed",
    serviceDueDate: "2027-06-01",
  },
  {
    id: "cu2",
    name: "Vikram Malhotra",
    address: "101 JM Road, Pune",
    mobile: "+91 9000004231",
    email: "vikram.malhotra@mail.com",
    vehicles: [
      {
        id: "v2a",
        mvNo: "MH-43-CQ-0274",
        work: "Fitness Renewal",
        insurance: "2027-03-15",
        fitness: "2027-02-28",
        tax: "Paid",
        status: "In Progress",
      },
      {
        id: "v2b",
        mvNo: "MH-43-CQ-0911",
        work: "Tax Payment",
        insurance: "2026-11-20",
        fitness: "2026-10-05",
        tax: "Due",
        status: "Pending",
      },
    ],
    serviceType: "Fitness",
    serviceStatus: "In Progress",
    serviceDueDate: "2027-02-28",
  },
  {
    id: "cu3",
    name: "Anita Desai",
    address: "102 MG Road, Pune",
    mobile: "+91 9000008462",
    email: "anita.desai@mail.com",
    vehicles: [
      {
        id: "v3a",
        mvNo: "MH-09-DX-0411",
        work: "Ownership Transfer",
        insurance: "2026-08-30",
        fitness: "2026-09-15",
        tax: "Paid",
        status: "In Progress",
      },
      {
        id: "v3b",
        mvNo: "MH-09-DX-1055",
        work: "Commercial Permit",
        insurance: "2027-01-10",
        fitness: "2027-01-20",
        tax: "Paid",
        status: "Pending",
      },
      {
        id: "v3c",
        mvNo: "MH-09-DX-2200",
        work: "Insurance Renewal",
        insurance: "2026-12-05",
        fitness: "2026-11-30",
        tax: "Due",
        status: "On Hold",
      },
    ],
    serviceType: "RC Transfer",
    serviceStatus: "In Progress",
    serviceDueDate: "2026-08-30",
  },
  {
    id: "cu4",
    name: "Rohan Gupta",
    address: "103 JM Road, Pune",
    mobile: "+91 9000012693",
    email: "rohan.gupta@mail.com",
    vehicles: [
      {
        id: "v4a",
        mvNo: "MH-12-EE-0548",
        work: "Fitness + Insurance",
        insurance: "2027-04-22",
        fitness: "2027-03-18",
        tax: "Paid",
        status: "Completed",
      },
    ],
    serviceType: "Insurance",
    serviceStatus: "Completed",
    serviceDueDate: "2027-04-22",
  },
  {
    id: "cu5",
    name: "Sneha Mishra",
    address: "104 Aundh, Pune",
    mobile: "+91 9000016924",
    email: "sneha.mishra@mail.com",
    vehicles: [
      {
        id: "v5a",
        mvNo: "MH-12-FM-0685",
        work: "New Registration",
        insurance: "2027-07-11",
        fitness: "2027-06-30",
        tax: "Paid",
        status: "Pending",
      },
      {
        id: "v5b",
        mvNo: "MH-12-FM-1100",
        work: "Tax Payment",
        insurance: "2026-10-01",
        fitness: "2026-09-25",
        tax: "Due",
        status: "In Progress",
      },
    ],
    serviceType: "License New",
    serviceStatus: "Pending",
    serviceDueDate: "2027-07-11",
  },
  {
    id: "cu6",
    name: "Arjun Nair",
    address: "105 Kothrud, Pune",
    mobile: "+91 9000021155",
    email: "arjun.nair@mail.com",
    vehicles: [
      {
        id: "v6a",
        mvNo: "MH-14-GN-0732",
        work: "Insurance Renewal",
        insurance: "2027-02-14",
        fitness: "2027-01-31",
        tax: "Paid",
        status: "Completed",
      },
    ],
    serviceType: "Insurance",
    serviceStatus: "Completed",
    serviceDueDate: "2027-02-14",
  },
  {
    id: "cu7",
    name: "Pooja Rao",
    address: "106 Deccan, Pune",
    mobile: "+91 9000025386",
    email: "pooja.rao@mail.com",
    vehicles: [
      {
        id: "v7a",
        mvNo: "MH-15-HR-0819",
        work: "Fitness Renewal",
        insurance: "2026-07-20",
        fitness: "2026-08-10",
        tax: "Paid",
        status: "In Progress",
      },
      {
        id: "v7b",
        mvNo: "MH-15-HR-1403",
        work: "Permit Renewal",
        insurance: "2027-05-05",
        fitness: "2027-04-25",
        tax: "Paid",
        status: "Pending",
      },
    ],
    serviceType: "Fitness",
    serviceStatus: "In Progress",
    serviceDueDate: "2026-08-10",
  },
  {
    id: "cu8",
    name: "Suresh Pawar",
    address: "107 Hadapsar, Pune",
    mobile: "+91 9000029617",
    email: "suresh.pawar@mail.com",
    vehicles: [
      {
        id: "v8a",
        mvNo: "MH-20-JK-0956",
        work: "Ownership Transfer",
        insurance: "2026-09-18",
        fitness: "2026-10-30",
        tax: "Due",
        status: "On Hold",
      },
    ],
    serviceType: "RC Transfer",
    serviceStatus: "On Hold",
    serviceDueDate: "2026-09-18",
  },
  {
    id: "cu9",
    name: "Meena Kulkarni",
    address: "108 Viman Nagar, Pune",
    mobile: "+91 9000033848",
    email: "meena.kulkarni@mail.com",
    vehicles: [
      {
        id: "v9a",
        mvNo: "MH-14-LM-1043",
        work: "Insurance + Tax",
        insurance: "2027-08-01",
        fitness: "2027-07-15",
        tax: "Paid",
        status: "Completed",
      },
      {
        id: "v9b",
        mvNo: "MH-14-LM-1890",
        work: "New Registration",
        insurance: "2027-09-20",
        fitness: "2027-08-31",
        tax: "Paid",
        status: "Pending",
      },
    ],
    serviceType: "Tax",
    serviceStatus: "Completed",
    serviceDueDate: "2027-08-01",
  },
  {
    id: "cu10",
    name: "Deepak Joshi",
    address: "109 Baner, Pune",
    mobile: "+91 9000038079",
    email: "deepak.joshi@mail.com",
    vehicles: [
      {
        id: "v10a",
        mvNo: "MH-11-NP-1130",
        work: "Fitness Renewal",
        insurance: "2026-11-05",
        fitness: "2026-12-20",
        tax: "Paid",
        status: "In Progress",
      },
    ],
    serviceType: "PUC",
    serviceStatus: "In Progress",
    serviceDueDate: "2026-12-20",
  },
];

export async function seedInitialData(): Promise<void> {
  const writes: Promise<void>[] = [];

  for (const r of seedClients) {
    const { id, ...data } = r;
    writes.push(setDoc(doc(db, "registry_clients", id), data));
  }
  for (const r of seedLeads) {
    const { id, ...data } = r;
    writes.push(setDoc(doc(db, "registry_leads", id), data));
  }
  for (const c of seedCustomers) {
    const { id, ...data } = c;
    writes.push(setDoc(doc(db, "registry_customers", id), data));
  }

  await Promise.all(writes);
}
